---
name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
      - feat
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bugfix
      - bug
  - title: 🧰 Maintenance
    labels:
      - chore
      - dependencies
  - title: 📚 Documentation
    labels:
      - documentation
      - docs
  - title: ⚡ Performance
    labels:
      - performance
      - perf
  - title: 🔨 Refactoring
    labels:
      - refactor
  - title: 🧪 Tests
    labels:
      - test
      - testing

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
# You can add # and @ to disable mentions, and add ` to disable code blocks.
change-title-escapes: \<*_&

version-resolver:
  major:
    labels:
      - major
      - breaking
  minor:
    labels:
      - minor
      - feature
      - feat
      - enhancement
  patch:
    labels:
      - patch
      - fix
      - bugfix
      - bug
      - chore
      - docs
      - documentation
      - dependencies
      - refactor
      - performance
      - test
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: >
    https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## Contributors

  $CONTRIBUTORS
