---
# This workflow deploys to PROD.
# The trigger should be:
# on:
#   push:
#     branches:
#       - main
name: "🚀 Deploy PROD"

run-name: "${{ github.workflow }} by ${{ github.actor }}"

on:
  workflow_call:

jobs:
  deploy:
    name: "Deploy Prod"
    uses: ./.github/workflows/sub-deploy-main.yml
    secrets: inherit
