---
# This workflow deploys to DEV.
# The trigger should be:
# on:
#   push:
#     branches:
#       - dev
name: "🚀 Deploy DEV"

run-name: "${{ github.workflow }} by ${{ github.actor }}"

on:
  workflow_call:

jobs:
  deploy-pre:
    name: "Deploy Preview"
    uses: ./.github/workflows/sub-deploy-dev.yml
    secrets: inherit
