---
name: "[SUB] Code Validation"

on:
  workflow_call:

jobs:
  trufflehog:
    name: "Trufflehog"
    uses: ./.github/workflows/sub-trufflehog.yml

  cypress:
    name: "Cypress"
    uses: ./.github/workflows/sub-cypress.yml
    secrets: inherit

  lint:
    name: "Lint"
    uses: ./.github/workflows/sub-linting.yml
