---
name: "[SUB] Linting"

on:
  workflow_call:

jobs:
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ESLint dependencies
        shell: bash
        run: npm install --force

      - name: Trunk Check
        uses: trunk-io/trunk-action@main
        with:
          cache: false
