---
# Example workflow file to be placed in client project repositories
# Path: .github/workflows/ci-cd.yaml

name: CI/CD Pipeline

on:
  push:
    branches: [develop, main, feature/**, hotfix/**, release/**]
  pull_request:
    branches: [develop, main]
  workflow_dispatch:
    inputs:
      release:
        description: Trigger a release
        required: false
        type: boolean
        default: false

jobs:
  # Update release drafts when PRs are merged to main branch
  update-release-draft:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: navigaite/workflow-test/.github/workflows/release-drafter.yaml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  security-scan:
    if: github.event_name != 'workflow_dispatch' || !github.event.inputs.release
    uses: navigaite/workflow-test/.github/workflows/security-scan.yaml@main
    with:
      # Use default branch for push events, PR base for pull_request events
      base-branch: >-
        ${{ github.event_name == 'pull_request' &&
            github.event.pull_request.base.ref || '' }}
      only-verified: true
      fail-on-detect: false

  lint:
    if: github.event_name != 'workflow_dispatch' || !github.event.inputs.release
    uses: navigaite/workflow-test/.github/workflows/lint.yaml@main
    with:
      node-version: 18
      lint-command: npm run lint
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  nextjs-pipeline:
    if: github.event_name != 'workflow_dispatch' || !github.event.inputs.release
    uses: navigaite/workflow-test/.github/workflows/nextjs-pipeline.yaml@main
    with:
      node-version: 18
    secrets:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

  # This job is triggered when the workflow is manually dispatched
  # with the release input set to true
  release:
    if: >-
      ${{ github.event.inputs.release &&
        (startsWith(github.ref, 'refs/heads/release/') ||
        startsWith(github.ref, 'refs/heads/hotfix/')) }}
    uses: navigaite/workflow-test/.github/workflows/release.yaml@main
    with:
      node-version: 18
      production-branch: main
      develop-branch: develop
      release-prefix: release/
      hotfix-prefix: hotfix/
      # Path to custom changelog configuration
      changelog-config-path: .github/changelog-config.json
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      # Optional: Use GitHub App for better permissions
      app-id: ${{ secrets.WORKFLOW_APP_ID }}
      app-private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}
