---
# This workflow creates a release on merges of PRs to the main branch.
# It deploys the main branch to PROD, creates a github release and a back-merge PR.
# The trigger should be:
# pull_request:
#   branches:
#       - main
#   types:
#       - closed
name: "📦 Release created"

run-name: "${{ github.workflow }} by ${{ github.actor }}"

on:
  workflow_call:

jobs:
  create-release:
    if:
      github.event.pull_request.merged == true && (startsWith(github.event.pull_request.head.ref,
      'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix/'))
    name: "Create Release"
    permissions:
      contents: write
      discussions: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Generate a github token
        id: generate-token
        uses: actions/create-github-app-token@2986852ad836768dfea7781f31828eb3e17990fa
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Get Current Version
        id: version
        run: echo "current_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          custom_tag: ${{ steps.version.outputs.current_version }}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: "./.github/changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          body: ${{steps.github_release.outputs.changelog}}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}

      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          source_branch: main
          target_branch: dev
          title: "ci: Back-Merge Release ${{ steps.version.outputs.current_version }}"
          body: |
            **Automated pull request!**

            This PR merges the newest release back into dev. Release: **${{ steps.version.outputs.current_version }}**
          label: "type: ci 🔄,automated pr 🤖,back-merge ⬅️"
          draft: false
