name: Lint

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        type: string
        default: "18"
      trunk-auto-fix:
        description: "Whether to auto-fix issues with Trunk"
        required: false
        type: boolean
        default: false
      eslint-args:
        description: "Additional arguments for ESLint"
        required: false
        type: string
        default: ""
    secrets:
      github-token:
        description: "GitHub token for authentication"
        required: true

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx ${{ inputs.eslint-args }}
        continue-on-error: true

      - name: Run Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          trunk-token: ${{ secrets.github-token }}
          check-mode: all
          arguments: --github-annotate ${{ inputs.trunk-auto-fix && '--fix' || '' }}

      - name: Check package.json formatting
        run: npx prettier -c package.json

      - name: Upload lint reports
        uses: actions/upload-artifact@v3
        with:
          name: lint-reports
          path: |
            eslint-report.json
            trunk-report.json
          if-no-files-found: ignore
