---
name: 📤 Promote dev → main
on:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  promote:
    uses: navigaite/.github/.github/workflows/promote-to-main.yaml@v3
