name: Release Drafter

on:
  workflow_call:
    inputs:
      target-branch:
        description: "Target branch for drafting releases (usually main)"
        required: false
        type: string
        default: "main"
      config-name:
        description: "Name of the Release Drafter configuration file"
        required: false
        type: string
        default: "release-drafter.yml"
    secrets:
      github-token:
        description: "GitHub token with repo scope"
        required: true

  # You can uncomment this section if you want to enable automatic runs on push to main
  # push:
  #   branches:
  #     - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: ${{ inputs.config-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
