---
name: "[SUB] Preview Deployment"

on:
  workflow_call:
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  vercel-deploy-preview:
    name: Vercel Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Generate a github token
        id: generate-token
        uses: actions/create-github-app-token@2986852ad836768dfea7781f31828eb3e17990fa
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@37.8.0

      - name: Deploy to Vercel Action
        uses: iFixit/deploy-to-vercel-action@master
        with:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_SCOPE: maimaldrei-navigaite
          GITHUB_DEPLOYMENT: true
          GITHUB_DEPLOYMENT_ENV: Development
          PR_LABELS: "deployed  🚀"
          PRODUCTION: false
          ALIAS_DOMAINS: |
            ${{ github.event.repository.name }}-dev.vercel.app
          PR_PREVIEW_DOMAIN: "${{ github.event.repository.name }}-dev.vercel.app"
          FORCE: true
