---
name: "[SUB] Release Deployment"

on:
  workflow_call:
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  vercel-deploy-preview:
    name: Vercel Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Generate a github token
        id: generate-token
        uses: actions/create-github-app-token@2986852ad836768dfea7781f31828eb3e17990fa
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: npm install

      - name: Get Current Version
        id: version
        run:
          echo "current_version=$(node -p "require('./package.json').version.replace(/\./g, '-')")"
          >> $GITHUB_OUTPUT

      - name: Install Vercel CLI
        run: npm install -g vercel@37.8.0

      - name: Deploy to Vercel Action
        uses: iFixit/deploy-to-vercel-action@master
        env:
          BRANCH: ${{ github.head_ref }}
        with:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_SCOPE: maimaldrei-navigaite
          GITHUB_DEPLOYMENT: true
          GITHUB_DEPLOYMENT_ENV: Preview
          PR_LABELS: "deployed  🚀"
          PRODUCTION: false
          ALIAS_DOMAINS: |
            ${{ github.event.repository.name }}-release-${{ steps.version.outputs.current_version }}.vercel.app
          PR_PREVIEW_DOMAIN: "${{ github.event.repository.name }}-release-${{ steps.version.outputs.current_version }}.vercel.app"
          FORCE: true
