---
name: "[SUB] Trufflehog"

on:
  workflow_call:

jobs:
  trufflehog:
    name: TruffleHog OSS
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@c9e60866440d9bd0925a31ce6edbc7ceed9a4000
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
