---
name: "[SUB] Branch Deployment"

on:
  workflow_call:
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  vercel-deploy-preview:
    name: Vercel Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Generate a github token
        id: generate-token
        uses: actions/create-github-app-token@2986852ad836768dfea7781f31828eb3e17990fa
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}

      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@0f16bc3af7db7d5171bf68bff6f82679de195113
        env:
          BRANCH: ${{ github.head_ref }}
        with:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_SCOPE: maimaldrei-navigaite
          GITHUB_DEPLOYMENT: true
          GITHUB_DEPLOYMENT_ENV: Preview
          PR_LABELS: "deployed  🚀"
          PRODUCTION: false
          ALIAS_DOMAINS: |
            ${{ github.event.repository.name }}-PR-{PR}.vercel.app
          PR_PREVIEW_DOMAIN: "${{ github.event.repository.name }}-PR-{PR}.vercel.app"
