---
on:
  workflow_call:
    inputs:
      vercel_scope:
        description: The scope of the Vercel project. e.g. maimaldrei-navigaite
        required: true
        type: string

permissions: read-all

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  vercel-deploy:
    name: 🚀 Vercel Deployment
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Generate a github token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}

      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📂 Debug Directory Contents
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Does package.json exist? $(test -f ./package.json && echo 'Yes' || echo 'No')"
          echo "Checking current branch and commit: $(git rev-parse --abbrev-ref HEAD) - $(git rev-parse HEAD)"

      - name: 🔖 Get Current Version
        id: version
        run: |
          if [ -f "./package.json" ]; then
            VERSION=$(node -p "try { \
              require('./package.json').version.replace(/\\./g, '-') \
            } catch(e) { \
              console.error('Error parsing package.json:', e); \
              process.exit(1) \
            }")
            echo "Extracted version: $VERSION"
            echo "current_version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "package.json not found. Using 'dev' as fallback version"
            echo "current_version=dev" >> $GITHUB_OUTPUT
          fi

      - name: 📦 Install Vercel CLI
        run: npm install -g vercel@latest

      - name: 🚀 Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@latest
        env:
          BRANCH: ${{ github.head_ref }}
        with:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_SCOPE: ${{ inputs.vercel_scope }}
          GITHUB_DEPLOYMENT: true
          GITHUB_DEPLOYMENT_ENV: Preview
          PR_LABELS: deployed  🚀
          PRODUCTION: false
          ALIAS_DOMAINS: |
            ${{ github.event.repository.name }}-release-${{ steps.version.outputs.current_version }}.vercel.app
          PR_PREVIEW_DOMAIN: |
            ${{ github.event.repository.name }}-release-${{ steps.version.outputs.current_version }}.vercel.app
          FORCE: true
